Hash bytestrings instead of unicode in UserDatabase
`hashlib.sha1` requires bytestrings, so we need to cast the parameters.

Relevant stacktrace:
```
Traceback (most recent call last):
  File "/home/mike/Proyectos/pyreload/module/database/DatabaseBackend.py", line 95, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/home/mike/Proyectos/pyreload/module/database/UserDatabase.py", line 51, in addUser
    h = sha1(salt + password)
TypeError: Unicode-objects must be encoded before hashing
```