Fix __slots__ error in PyFile class
Python 2 doesn't complain about invalid values for `__slots__`, but
Python 3 requires it to be correct. As `size` is being defined as a
property, it can't be a class slot.

Related stacktrace:
```
Traceback (most recent call last):
  File "./pyLoadCore.py", line 67, in <module>
    from module.database import DatabaseBackend, FileHandler
  File "/home/mike/Proyectos/pyreload/module/database/__init__.py", line 4, in <module>
    from .FileDatabase import FileHandler
  File "/home/mike/Proyectos/pyreload/module/database/FileDatabase.py", line 27, in <module>
    from module.PyFile import PyFile
  File "/home/mike/Proyectos/pyreload/module/PyFile.py", line 55, in <module>
    class PyFile(object):
ValueError: 'size' in __slots__ conflicts with class variable
```