Fix version check in ConfigParser for Python 3
Python 3 was accessing to the conf files in binary mode, but checking
their contents using unicode instead.

Relevant stacktrace:
```
Traceback (most recent call last):
  File "/home/mike/Proyectos/pyreload/module/ConfigParser.py", line 78, in checkVersion
    v = v[v.find(":") + 1:].strip()
TypeError: a bytes-like object is required, not 'str'
```